@accountHost = http://localhost:8081
@transferHost = http://localhost:8082

@adminEmail = admin@compliflow.local
@adminPassword = secret123

### LOGIN
POST {{accountHost}}/api/auth/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}